#!/usr/bin/env bash

# Check if running by root
if [[ $EUID -ne 0 ]]; then echo -e 'This script must be run as root' ; exit 1 ; fi

if [ -z "$1" ] || [ -z "$2" ] ; then
    echo -e "\nPlease input the directory name and the owner."
    echo -e "\nExample: $(basename "$0") /srv/domain.com user:group\n"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo -e "\nDirectory $1 doesn't exists!\n"
    exit 1
else
    echo -e "\nSetting up permission for directory..."
    find "$1/." -type d -exec chmod 00775 {} \;
    find "$1/." -type f -exec chmod 00644 {} \;
    chown -R "$2" "$1/";
fi

echo -e "\nPermission for directory $1 has fixed!\n"
