#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi

if [[ $(mysql mysql -e "select Db, User, Host from db") ]]; then
    echo ; mysql mysql -e "select Db, User, Host from db;" ; echo
fi
