#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi

MYSQL=`which mysql`

if [[ $($MYSQL mysql -e "select Db, User, Host from db") ]]; then
    echo
    $MYSQL mysql -e "select Db, User, Host from db;"
else
    echo -e "\nNo databased needs to be deleted.\n"
    exit 1
fi

# The wizard
echo
read -e -p "Database Name     : " db_name
read -e -p "Database User     : " -i "$db_name" db_user
read -e -p "Database Host     : " -i "127.0.0.1" db_host

# Drop database and user
$MYSQL -e "DROP DATABASE IF EXISTS $db_name"
$MYSQL -e "DROP USER IF EXISTS '$db_name'@'$db_host'"
$MYSQL -e "FLUSH PRIVILEGES"

echo -e "\nDatabase $db_name @ $db_host has been dropped.\n"
