#!/usr/bin/env bash

BOT_KEY="VAR_BOTKEY"
CHAT_ID="VAR_CHATID"

URL="https://api.telegram.org/bot${BOT_KEY}/sendMessage"
DATE="$(date "+%d %b %Y %H:%M")"

if [ -n "$SSH_CLIENT" ]; then
  CLIENT_IP=$(echo $SSH_CLIENT | awk '{print $1}')

  SRV_HOSTNAME=$(hostname -f)
  SRV_IP=$(hostname -I | awk '{print $1}')

  IPINFO="https://ipinfo.io/${CLIENT_IP}"

  MESSAGE="User ${USER} logged in to *${SRV_HOSTNAME}*
Server IP: *${SRV_IP}*
Client IP: *${CLIENT_IP}*
Date Time: ${DATE}
User info: [${IPINFO}](${IPINFO})"

  curl -s -d "chat_id=${CHAT_ID}&text=${MESSAGE}&disable_web_page_preview=true&parse_mode=markdown" $URL > /dev/null
fi
