#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi

CERTBOT=`which certbot`

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

www=""

read -ep "Generate certificate for www subdomain?   yes/no : " answer

if [[ "${answer,,}" =~ ^(yes|y)$ ]] ; then www="-d www.$1" ; fi

systemctl stop nginx

$CERTBOT certonly --standalone --rsa-key-size 4096 --agree-tos --register-unsafely-without-email -d $1 $www

systemctl restart nginx

echo -e "SSL certificate for $1 created..."
