#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi

CERTBOT=`which certbot`

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

read -p "Press enter to continue ..."

systemctl stop nginx

$CERTBOT certonly \
    --manual \
    --agree-tos \
    --no-bootstrap \
    --rsa-key-size 4096 \
    --manual-public-ip-logging-ok \
    --preferred-challenges dns-01 \
    --server https://acme-v02.api.letsencrypt.org/directory \
    -d $1 -d *.$1

$CERTBOT certificates | grep Domains:

systemctl restart nginx

echo -e "Wildcard SSL certificate for $1 created..."
