#!/usr/bin/env bash

# Check if running by root
if [[ $EUID -ne 0 ]]; then echo -e 'This script must be run as root' ; exit 1 ; fi

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

# Validate existing vhost
if [[ -f "/etc/nginx/vhost.d/$1.conf" ]]; then
    echo -e "\nVirtualHost already exist...\n"
    exit 1
else
    cp /etc/nginx/manifest/vhost-proxy.cnf /etc/nginx/vhost.d/$1.conf
    sed -i "s/HOSTNAME/$1/" /etc/nginx/vhost.d/$1.conf
    echo
fi

# Configure reverse proxy host
read -ep "Enter app identifier        (ex: my_application) : " app_id
sed -i "s/APP_NAME/$app_id/" /etc/nginx/vhost.d/$1.conf

read -ep "Enter application host and port                  : " -i "127.0.0.1:2368" app_host
sed -i "s/APP_HOST/$app_host/" /etc/nginx/vhost.d/$1.conf

read -ep "Do you want to use www subdomain?         yes/no : " answer
if [[ "${answer,,}" =~ ^(yes|y)$ ]] ; then
    sed -i "s/# server_name www/server_name www/" /etc/nginx/vhost.d/$1.conf
fi

# Supervisor configuration (gunicorn is a sample)
cat > /etc/supervisor/conf.d/${app_id}.conf-disable <<EOF
[program:${app_id}]
directory=/srv/$1
# environment=APP_ENV=live
# command=/srv/$1/.venv/bin/gunicorn -b ${app_host} app:app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/$1-err.log
stdout_logfile=/var/log/supervisor/$1-out.log
EOF

# Creating web directory
mkdir -p /srv/$1/public
chown -R www-data: /srv/$1
chmod -R 00775 /srv/$1

# Ask to generate LetsEncrypt certificate
read -ep "Generate LetsEncrypt certificate?         yes/no : " answer

if [[ "${answer,,}" =~ ^(yes|y)$ ]] ; then
    bash /usr/local/bin/ssl-create $1
fi

# Reload supervisor
echo
read -ep "Do you want to reload supervisor daemon?  yes/no : " answer
if [[ "${answer,,}" =~ ^(yes|y)$ ]] ; then
    supervisorctl reread
    systemctl restart supervisor
    systemctl status supervisor | grep Active
    supervisorctl status
fi

# Test nginx configuration then restart
`which nginx` -t 2>/dev/null > /dev/null
if [[ $? == 0 ]]; then
    echo -e "\nReloading Nginx configuration..."
    systemctl restart nginx
else
    echo -e "\nNginx configuration fail..."
    `which nginx` -t
    exit
fi

echo -e "VirtualHost for $1 created...\n"
