#!/usr/bin/env bash

# Check if running by root
if [[ $EUID -ne 0 ]]; then echo -e 'This script must be run as root' ; exit 1 ; fi

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

# Validate existing vhost
if [[ -f "/etc/nginx/vhost.d/$1.conf" ]]; then
    echo -e "\nVirtualHost already exist...\n"
    exit 1
fi

# Virtual Host Configuration
cp /etc/nginx/manifest/wpmu-master.cnf /etc/nginx/vhost.d/$1.conf
sed -i "s/HOSTNAME/$1/" /etc/nginx/vhost.d/$1.conf
sed -i "s/HOSTNAME/$1/" /etc/nginx/vhost.d/$1.conf

# Create Web directory
mkdir -p /srv/$1/public

if [[ ! -f "/srv/$1/public/index.php" ]]; then
    cp /etc/nginx/manifest/default.tpl /srv/$1/public/index.php
fi

# Set directory permission
chown -R www-data: /srv/$1
chmod -R 00775 /srv/$1

# Ask to generate LetsEncrypt certificate
echo
read -ep "Generate wildcard SSL certificate?  yes/no : " answer

if [[ "${answer,,}" =~ ^(yes|y)$ ]] ; then
    bash /usr/local/bin/ssl-wildcard $1
fi

systemctl restart nginx

echo -e "\nVirtualHost for $1 created...\n"
