#!/usr/bin/env bash

# Check if running by root
if [[ $EUID -ne 0 ]]; then echo -e 'This script must be run as root' ; exit 1 ; fi

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

# Validate existing vhost
if [[ -f "/etc/nginx/vhost.d/$1.conf" ]]; then
    echo -e "\nVirtualHost already exist...\n"
    exit 1
fi

AskMasterDomain() {
    echo
    read -ep "Master domain for WP-MU?          : " wpDomain
    if [[ "$wpDomain" == "" ]] ; then AskMasterDomain ; fi
}
AskMasterDomain

# Virtual Host Configuration
cp /etc/nginx/manifest/wpmu-domain.cnf /etc/nginx/vhost.d/$1.conf
sed -i "s/WPDOMAIN/$wpDomain/" /etc/nginx/vhost.d/$1.conf
sed -i "s/HOSTNAME/$1/" /etc/nginx/vhost.d/$1.conf
sed -i "s/HOSTNAME/$1/" /etc/nginx/vhost.d/$1.conf

# Ask to generate LetsEncrypt certificate
read -ep "Generate SSL certificate?  yes/no : " answer

if [[ "${answer,,}" =~ ^(yes|y)$ ]] ; then
    bash /usr/local/bin/ssl-create $1
fi

# Test nginx configuration then restart
`which nginx` -t 2>/dev/null > /dev/null
if [[ $? == 0 ]]; then
    echo -e "\nReloading Nginx configuration..."
    systemctl restart nginx
else
    echo -e "\nNginx configuration fail..."
    `which nginx` -t
    exit
fi

echo -e "VirtualHost for $1 created...\n"
