#!/usr/bin/env python
#
# This is a small cli utilities for managing your server.
#

import os
import click
import pkg_resources
from utils import logger as logger

VERSION = pkg_resources.require('stk')[0].version

# Privilages check
if os.getuid() is not 0:
    print("You are not root!")
    exit(1)

@click.group()
@click.version_option(version=VERSION, prog_name='elsa')
def cli():
    pass

@cli.command()
def sysupdate():
    os.system('apt update ; apt full-upgrade -y')
    os.system('apt autoremove -y ; apt clean')

@cli.command()
@click.option('--type', default='html', help='Type of site [html|php|ghost|python|proxy]')
@click.argument('name')
def site(type, name):
    click.echo('Creating virtualhost {} for {}'.format(type,name))

if __name__ == "__main__":
    cli()
