#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
nocolor='\033[0m'
green='\033[0;32m'
red='\033[0;33m'
blue='\033[0;34m'

#----------------------------------------------------------------------------------
# --
#----------------------------------------------------------------------------------
if [ -z $1 ] ; then
    echo -e "\nPlease input the directory name."
    echo -e "\nExample: $(basename $0) /srv/web/domain.com\n"
    exit 1
fi

# Check directory
if [ ! -d $1 ]; then
    echo -e "\n${red}Directory $1 doesn't exists!\n${nocolor}"
    exit 1
fi

echo -e "\n${green}Setting up file and directory permission...${nocolor}"

# Convert path type
dirPath=$1
if [[ $1 =~ "." ]] ; then
    dirPath=$(cd ${1}; pwd)
fi

# Change permission
find "$dirPath/." -type d -exec chmod 0777 {} \;
find "$dirPath/." -type f -exec chmod 0644 {} \;
chmod -R 0770 $dirPath/* && chmod 0777 $dirPath

# Change owner
[[ $2 ]] && chown -R $2 $dirPath|| chown -R webmaster:webmaster $dirPath

echo -e "\n${green}Permission for directory $dirPath has been fixed!\n${nocolor}"
