#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
nocolor='\033[0m'
green='\033[0;32m'
red='\033[0;33m'
blue='\033[0;34m'

#----------------------------------------------------------------------------------
# --
#----------------------------------------------------------------------------------
if [ -z $1 ] ; then
    echo -e "\nPlease input the directory name."
    echo -e "\nExample: $(basename $0) /srv/web/domain.com\n"
    exit 1
fi

# Check directory
if [ ! -d $1 ]; then
    echo -e "\n${red}Directory $1 doesn't exists!\n${nocolor}"
    exit 1
fi

echo -e "\n${green}Setting up file and directory permission...${nocolor}"

# Change permission
find "$1/." -type d -exec chmod 0777 {} \;
find "$1/." -type f -exec chmod 0644 {} \;
chmod -R 0770 $1/* && chmod 0777 $1

# Change owner
[[ $2 ]] && chown -R $2 $1|| chown -R webmaster:webmaster $1

echo -e "\n${green}Permission for directory $1 has been fixed!${nocolor}"
