#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
nocolor='\033[0m'
green='\033[0;32m'
red='\033[0;33m'
blue='\033[0;34m'

#----------------------------------------------------------------------------------
# --
#----------------------------------------------------------------------------------

if [ -z "$1" ] ; then
    echo -e "\nPlease input the database name."
    echo -e "\nExample: $(basename "$0") awesomedb\n"
    exit 1
fi

# Check if database already exist
CHECK=`mysql -e "SHOW DATABASES" | grep $1`
if [ "$CHECK" == "$1" ]; then
    echo -e "\nDatabase already exists!\n" ; exit 1
else
    db_name=$1
fi

# Database password
read -e -p "Database Password : " -i "auto" ask_db_pass
if [ "$ask_db_pass" == "auto" ] ;then
    # passlen=`shuf -i 8-16 -n 1`
    passlen=`echo $1 | wc -c`
    db_pass=`pwgen -scn $passlen 1`
else
    db_pass=$ask_db_pass
fi

read -e -p "Database Address  : " -i "127.0.0.1" db_addr

# Create database and user
mysql -e "CREATE DATABASE IF NOT EXISTS $db_name"
mysql -e "CREATE USER IF NOT EXISTS '$db_name'@'$db_addr' IDENTIFIED BY '$db_pass'"
mysql -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_name'@'$db_addr'"
mysql -e "FLUSH PRIVILEGES"

echo -e "\nDatabase created with user $db_name and password: $db_pass\n"
