#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
nocolor='\033[0m'
green='\033[0;32m'
red='\033[0;33m'
blue='\033[0;34m'

#----------------------------------------------------------------------------------
# --
#----------------------------------------------------------------------------------

if [[ $(mysql -e "select Db, User, Host from mysql.db") ]]; then
    echo ; mysql -e "select Db, User, Host from mysql.db;" ; echo
else
    echo -e "\nYou have no database!\n"
fi
