#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
nocolor='\033[0m'
green='\033[0;32m'
red='\033[0;33m'
blue='\033[0;34m'

#----------------------------------------------------------------------------------
# --
#----------------------------------------------------------------------------------

if [ -x $(which nginx) ]; then
    WEBSERVER="nginx"
elif [ -x $(which apache2) ]; then
    WEBSERVER="apache2"
fi

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

read -p "Press enter to continue ..."

systemctl stop $WEBSERVER

certbot certonly \
    --manual \
    --agree-tos \
    --no-bootstrap \
    --rsa-key-size 4096 \
    --manual-public-ip-logging-ok \
    --preferred-challenges dns-01 \
    --server https://acme-v02.api.letsencrypt.org/directory \
    -d $1 -d *.$1

systemctl restart $WEBSERVER

# certbot certificates | grep Domains:

echo -e "Wildcard SSL certificate for $1 created..."
