#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
nocolor='\033[0m'
green='\033[0;32m'
red='\033[0;33m'
blue='\033[0;34m'

#----------------------------------------------------------------------------------
# --
#----------------------------------------------------------------------------------

if [ -x $(which nginx) ]; then
    WEBSERVER="nginx"
elif [ -x $(which apache2) ]; then
    WEBSERVER="apache2"
fi

systemctl stop $WEBSERVER
certbot renew --no-self-upgrade
systemctl restart $WEBSERVER
