#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
NO='\033[0;33m' ; OK='\033[0;32m' ; NC='\033[0m'

# Initial Setup
#-----------------------------------------------------------------------------------------
TIMESTAMP=$(date +"%y%m%d")
HOSTNAME=$(hostname -s)
BACKUP_DIR="/usr/backup/$TIMESTAMP-$HOSTNAME"
BACKUP_PATH="$BACKUP_DIR/webdata"

mkdir -p $BACKUP_DIR

[ -d $BACKUP_PATH ] && rm -fr $BACKUP_PATH
[ -d $$BACKUP_PATH ] || mkdir -p $BACKUP_PATH

# Backup web directory
#-----------------------------------------------------------------------------------------
cd /srv
for i in */; do
    [ -d "$i" ] && tar -cpzf "$(basename -- $i).tar.gz" $i &>/dev/null
done

mv /srv/*tar.gz $BACKUP_PATH/

# Change permissions
#-----------------------------------------------------------------------------------------
chown -R webmaster:webmaster ${BACKUP_DIR}
