#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
NO='\033[0;33m' ; OK='\033[0;32m' ; NC='\033[0m'

if [ -z "$1" ] || [ -z "$2" ] ; then
    echo -e "\nPlease input the directory name and the owner."
    echo -e "\nExample: $(basename "$0") /srv/domain.com user:group\n"
    exit 1
fi

if [ ! -d "$1" ]; then echo -e "\nDirectory $1 doesn't exists!\n" ; exit 1 ; fi

echo -e "\nSetting up file and directory permission..."

chmod -R 0777 $1 ; chown -R $2 $1
find "$1/." -type d -exec chmod 0775 {} \;
find "$1/." -type f -exec chmod 0644 {} \;

echo -e "\n${OK}Permission for directory $1 has been fixed!${NC}"
