#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
NO='\033[0;33m' ; OK='\033[0;32m' ; NC='\033[0m'

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

password=$(echo "{md5}"`echo -n "secret" | openssl dgst -binary -md5 | openssl enc -base64`)

echo 'TODO!'

echo -e "FTP virtualHost for $1 created...\n"
