#!/bin/bash
if [[ $EUID -ne 0 ]]; then echo 'This script must be run as root' ; exit 1 ; fi
NO='\033[0;33m' ; OK='\033[0;32m' ; NC='\033[0m'

if [ -z "$1" ] ; then
    echo -e "\nPlease input the domain name."
    echo -e "\nExample: $(basename "$0") domain.com\n"
    exit 1
fi

if [[ ! -d "/etc/letsencrypt/live/$1" ]]; then
    echo -e "SSL certificate for $1 doesn't exist..."
    exit 1
fi

read -p "Press enter to continue ..."

certbot revoke --cert-path /etc/letsencrypt/live/$1/fullchain.pem

echo -e "SSL certificate for $1 has been revoked..."
